import Head from 'next/head'

export default function SEO () {
  return (
    <Head>
      <title>Projeto Shape</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/haltere.png" />
    </Head>
  )
}
