import Head from 'next/head'
import NavBar from '../src/components/NavBar'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Projeto Shape</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main>

      </main>

      <footer>
        <a href="https://www.flaticon.com/br/icones-gratis/exercite-se" title="exercite-se ícones">Exercite-se ícones criados por Freepik - Flaticon</a>
      </footer>
    </div>
  )
}
